import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = 'definitions/autogen';

console.log('Resolving cross-file dependencies...');

const typeToFile = new Map();
const generatedFiles = fs.readdirSync(OUT_DIR).filter(f => f.endsWith('.ts'));

// 1. Map all exported types
for (const file of generatedFiles) {
    const content = fs.readFileSync(path.join(OUT_DIR, file), 'utf-8');
    const typeRegex = /export (?:interface|type|enum) ((?:CT|ST)_[A-Za-z0-9_]+)/g;
    let match;
    while ((match = typeRegex.exec(content)) !== null) {
        typeToFile.set(match[1], file.replace('.ts', ''));
    }
}

// 2. Add missing imports to each file
for (const file of generatedFiles) {
    let content = fs.readFileSync(path.join(OUT_DIR, file), 'utf-8');
    
    // Remove existing autogenerated imports if any (to avoid duplicates if rerun)
    content = content.replace(/^import \{ .* \} from '\.\/.*';\n/gm, '');
    content = content.trimStart();

    const definedTypes = new Set();
    const typeRegex = /export (?:interface|type|enum) ((?:CT|ST)_[A-Za-z0-9_]+)/g;
    let match;
    while ((match = typeRegex.exec(content)) !== null) {
        definedTypes.add(match[1]);
    }

    const referencedTypes = new Set();
    const refRegex = /\b((?:CT|ST)_[A-Za-z0-9_]+)\b/g;
    while ((match = refRegex.exec(content)) !== null) {
        const typeName = match[1];
        if (!definedTypes.has(typeName) && typeToFile.has(typeName)) {
            referencedTypes.add(typeName);
        }
    }

    if (referencedTypes.size > 0) {
        const importsByFile = new Map();
        for (const type of referencedTypes) {
            const sourceFile = typeToFile.get(type);
            if (sourceFile !== file.replace('.ts', '')) {
                if (!importsByFile.has(sourceFile)) {
                    importsByFile.set(sourceFile, new Set());
                }
                importsByFile.get(sourceFile).add(type);
            }
        }

        let importStatements = '';
        const sortedFiles = Array.from(importsByFile.keys()).sort();
        for (const sourceFile of sortedFiles) {
            const types = importsByFile.get(sourceFile);
            importStatements += `import { ${Array.from(types).sort().join(', ')} } from './${sourceFile}';\n`;
        }
        
        content = importStatements + '\n' + content;
        fs.writeFileSync(path.join(OUT_DIR, file), content);
    }
}

console.log('Post-processing completed.');
