/**
 * Common types shared across autogenerated definition files.
 * Semi-automatically refactored.
 */

export type ST_Guid = string;

export type ST_Xstring = string;

export type ST_TextLanguageID = string;

export interface CT_Extension {
  uri?: string;
}

export interface CT_ExtensionList {
  ext?: CT_Extension[];
}

export type ST_Panose = string;

export type ST_String = string;

export type ST_TwipsMeasure = string;

export interface CT_Text {
  val?: ST_String;
  space?: any;
}

export interface CT_TwipsMeasure {
  val: ST_TwipsMeasure;
}

export type ST_RelationshipId = string;

export type ST_ColorType = string;



export interface CT_Empty {}

export enum ST_TrueFalse {
  /** True */
  t = 't',
  /** False */
  f = 'f',
  /** True */
  true = 'true',
  /** False */
  false = 'false'
}